# -*- coding: utf-8 -*-
"""PRODIGY_GA_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZE-Bh1I7RPFyMQXjXb0mm4sXy0akHep
"""

!pip install transformers datasets torch accelerate

from datasets import load_dataset

ds = load_dataset("Abirate/english_quotes")
print(ds)

print(ds["train"][0])

from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

texts = ds["train"]["quote"]

print(texts[:5])

print("GPT-2 loaded successfully!")

from transformers import DataCollatorForLanguageModeling

def tokenize_function(examples):
    return tokenizer(
        examples["quote"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

tokenized_dataset = ds["train"].map(tokenize_function, batched=True)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print("Tokenization completed!")

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./gpt2_quotes",
    overwrite_output_dir=True,
    num_train_epochs=1,
    per_device_train_batch_size=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

trainer.train()

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./gpt2_quotes",
    num_train_epochs=1,
    per_device_train_batch_size=2
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

trainer.train()

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

result = generator(
    "Success is",
    max_length=50,
    num_return_sequences=1
)

print(result[0]["generated_text"])

from transformers import GPT2LMHeadModel

model = GPT2LMHeadModel.from_pretrained("gpt2")